/**
 * Centralized icon exports for better tree-shaking and code splitting
 * This helps reduce bundle size by consolidating icon imports
 */
import {
  LayoutDashboard,
  Calendar,
  Users,
  Briefcase,
  Building,
  Search,
  Receipt,
  TrendingUp,
  Lightbulb,
  DollarSign,
  PieChart,
  BarChart3,
  Activity,
  CreditCard,
  TrendingDown,
  FileSpreadsheet,
  Calculator,
  Scale,
  Download,
  TrendingDown as TrendingDownIcon,
  Award,
  Target,
  AlertTriangle,
  Shield,
  RefreshCw,
  Filter,
  AlertCircle,
  Clock,
} from 'lucide-react';

// Export all icons used across the application
export {
  LayoutDashboard,
  Calendar,
  Users,
  Briefcase,
  Building,
  Search,
  Receipt,
  TrendingUp,
  Lightbulb,
  DollarSign,
  PieChart,
  BarChart3,
  Activity,
  CreditCard,
  TrendingDown,
  FileSpreadsheet,
  Calculator,
  Scale,
  Download,
  TrendingDownIcon,
  Award,
  Target,
  AlertTriangle,
  Shield,
  RefreshCw,
  Filter,
  AlertCircle,
  Clock,
};
